### ISSUE TITLE
live555 rtsp stream and srs rtmp stream not supported

### ISSUE THREAD

**Issue by Lebron8997** [Fonbet/argus-tensor-stream#3]
I used a mkv file in live555 mediaServer folder to transcode the file as rtsp stream. It has been tested by vlc and opencv(cv2.VideoCapture) decode. But it failed with your nice project.
The following output:
`TID: 140544236140288 Error status != 0

TID: 140544236140288 src/Parser.cpp Init 285

TID: 140544236140288 Error status != 0

TID: 140544236140288 src/Wrappers/WrapperPython.cpp initPipeline 32

TID: 140544236140288 Error status != 0

TID: 140544236140288 src/Parser.cpp Init 285

TID: 140544236140288 Error status != 0

TID: 140544236140288 src/Wrappers/WrapperPython.cpp initPipeline 32

TID: 140544236140288 Error status != 0

TID: 140544236140288 src/Parser.cpp Init 285

TID: 140544236140288 Error status != 0

TID: 140544236140288 src/Wrappers/WrapperPython.cpp initPipeline 32

TID: 140544236140288 Error status != 0

TID: 140544236140288 src/Parser.cpp Init 285

TID: 140544236140288 Error status != 0

TID: 140544236140288 src/Wrappers/WrapperPython.cpp initPipeline 32

TID: 140544236140288 Error status != 0

TID: 140544236140288 src/Parser.cpp Init 285

TID: 140544236140288 Error status != 0

TID: 140544236140288 src/Wrappers/WrapperPython.cpp initPipeline 32

TID: 140544236140288 Error status != 0

TID: 140544236140288 src/Parser.cpp Init 285

TID: 140544236140288 Error status != 0

TID: 140544236140288 src/Wrappers/WrapperPython.cpp initPipeline 32

TID: 140544236140288 Error status != 0

TID: 140544236140288 src/Parser.cpp Init 285

TID: 140544236140288 Error status != 0

TID: 140544236140288 src/Wrappers/WrapperPython.cpp initPipeline 32

TID: 140544236140288 Error status != 0

TID: 140544236140288 src/Parser.cpp Init 285

TID: 140544236140288 Error status != 0

TID: 140544236140288 src/Wrappers/WrapperPython.cpp initPipeline 32

TID: 140544236140288 Error status != 0

TID: 140544236140288 src/Parser.cpp Init 285

TID: 140544236140288 Error status != 0

TID: 140544236140288 src/Wrappers/WrapperPython.cpp initPipeline 32

TID: 140544236140288 Error status != 0

TID: 140544236140288 src/Parser.cpp Init 285

TID: 140544236140288 Error status != 0

TID: 140544236140288 src/Wrappers/WrapperPython.cpp initPipeline 32

TID: 140544236140288 Error status != 0

TID: 140544236140288 src/Parser.cpp Init 285

TID: 140544236140288 Error status != 0

TID: 140544236140288 src/Wrappers/WrapperPython.cpp initPipeline 32

TID: 140544236140288 Error status != 0

TID: 140544236140288 src/Parser.cpp Init 285

TID: 140544236140288 Error status != 0

Traceback (most recent call last):

  File "runVideo.py", line 8, in <module>

    reader.initialize()

  File "/home/lxl/anaconda3.6/lib/python3.6/site-packages/tensor_stream-0.1.8-py3.6-linux-x86_64.egg/tensor_stream/tensor_stream.py", line 98, in initialize

RuntimeError: Can't initialize TensorStream
`
I also tested rtmp stream from file with srs. 

BTW, I compiled the project with cuda 9.0, ffmpeg and pytorch.

What should I do next?
Thank you!

**Comment by BykadorovR** [comment]
@Lebron8997 Could you please provide test stream so I can reproduce it locally?

**Comment by Lebron8997** [comment]
I tested the stream "rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov". Failed as above.
Would you please tell me your FFMPEG version?

OS: ubuntu 16.04
ffmpeg: 3.4.6
configuration: --enable-cuda --enable-cuvid --enable-nvenc --enable-nonfree --enable-libnpp --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64
cuda: 9.0
pytorch:1.1.0
python:3.6(anaconda 5.2)

info from  ldd TensorStream.cpython-36m-x86_64-linux-gnu.so
'
linux-vdso.so.1 =>  (0x00007ffd15bba000)

	libcudart.so.9.0 => /usr/local/cuda-9.0/lib64/libcudart.so.9.0 (0x00007f916d0cb000)

	libcuda.so.1 => /usr/lib/x86_64-linux-gnu/libcuda.so.1 (0x00007f916bf74000)

	libavcodec.so.57 => /home/xl/inst/ffmpeg-zoo/ffmpeg-3.4.6/lib/libavcodec.so.57 (0x00007f916a8fe000)

	libavdevice.so.57 => /home/xl/inst/ffmpeg-zoo/ffmpeg-3.4.6/lib/libavdevice.so.57 (0x00007f916a6ed000)

	libavfilter.so.6 => /home/xl/inst/ffmpeg-zoo/ffmpeg-3.4.6/lib/libavfilter.so.6 (0x00007f916a2bf000)

	libavformat.so.57 => /home/xl/inst/ffmpeg-zoo/ffmpeg-3.4.6/lib/libavformat.so.57 (0x00007f9169e88000)

	libavutil.so.55 => /home/xl/inst/ffmpeg-zoo/ffmpeg-3.4.6/lib/libavutil.so.55 (0x00007f9169c07000)

	libswresample.so.2 => /home/xl/inst/ffmpeg-zoo/ffmpeg-3.4.6/lib/libswresample.so.2 (0x00007f91699ea000)

	libswscale.so.4 => /home/xl/inst/ffmpeg-zoo/ffmpeg-3.4.6/lib/libswscale.so.4 (0x00007f9169763000)

	libstdc++.so.6 => /home/xl/anaconda3/lib/libstdc++.so.6 (0x00007f9169429000)

	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9169120000)

	libgcc_s.so.1 => /home/xl/anaconda3/lib/libgcc_s.so.1 (0x00007f9168f0e000)

	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9168cf1000)

	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9168927000)

	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9168723000)

	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f916851b000)

	libnvidia-fatbinaryloader.so.418.56 => /usr/lib/nvidia-418/libnvidia-fatbinaryloader.so.418.56 (0x00007f91682cd000)

	liblzma.so.5 => /home/xl/anaconda3/lib/liblzma.so.5 (0x00007f91680a7000)

	libz.so.1 => /home/xl/anaconda3/lib/libz.so.1 (0x00007f9167e90000)

	libxcb.so.1 => /home/xl/anaconda3/lib/libxcb.so.1 (0x00007f9167c67000)

	libxcb-shm.so.0 => /home/xl/anaconda3/lib/libxcb-shm.so.0 (0x00007f9167a63000)

	libxcb-xfixes.so.0 => /home/xl/anaconda3/lib/libxcb-xfixes.so.0 (0x00007f916785a000)

	libxcb-shape.so.0 => /home/xl/anaconda3/lib/libxcb-shape.so.0 (0x00007f9167656000)

	/lib64/ld-linux-x86-64.so.2 (0x00007f916d57c000)

	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f9167452000)

`

Thank you!

**Comment by BykadorovR** [comment]
We use ffmpeg from release/4.0 branch. You can find more ffmpeg build details here:
https://github.com/Fonbet/argus-tensor-stream/blob/master/docker/Dockerfile_cu9
BTW, thanks for additional details. I'm going to investigate the issue locally and return to you with solution.

**Comment by BykadorovR** [comment]
I tested your RTSP stream with release/4.0 and master FFmpeg branches and saw no issues, but had compilation errors with 3.4.6 release, I haven't investigated why compilation errors happened, though.
I see from log you attached that issue is related to FFmpeg demuxer so could you try to build FFmpeg either from release/4.0 or master branch?

**Comment by Lebron8997** [comment]
@BykadorovR Thank you very much for your solution. 
In fact, I tested your project with the following setup.py file, adding my compiled ffmpeg.
I have compiled ffmpeg 4.0 as you said in Dockerfile_cu9. To compile everything good I added line 
`#include <libavutil/hwcontext.h>`
in Decoder.cpp at line 6.
[setup.zip](https://github.com/Fonbet/argus-tensor-stream/files/3182437/setup.zip)

With that line added, I met error:

`Core dumped`

when reader.initialize().


Without that line, I met the following problem when compiling:

`/home/xl/anaconda3/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'

  warnings.warn(msg)

running build

running build_py

creating build

creating build/lib.linux-x86_64-3.6

creating build/lib.linux-x86_64-3.6/tensor_stream

copying tensor_stream/__init__.py -> build/lib.linux-x86_64-3.6/tensor_stream

copying tensor_stream/tensor_stream.py -> build/lib.linux-x86_64-3.6/tensor_stream

running build_ext

building 'TensorStream' extension

creating build/temp.linux-x86_64-3.6

creating build/temp.linux-x86_64-3.6/src

creating build/temp.linux-x86_64-3.6/src/Wrappers

gcc -pthread -B /home/xl/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xl/anaconda3/lib/python3.6/site-packages/torch/include -I/home/xl/anaconda3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/xl/anaconda3/lib/python3.6/site-packages/torch/include/TH -I/home/xl/anaconda3/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -Iinclude/ -Iinclude/Wrappers/ -I/home/xl/anaconda3/include/python3.6m -c src/Decoder.cpp -o build/temp.linux-x86_64-3.6/src/Decoder.o -g -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=TensorStream -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11

cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
src/Decoder.cpp: In member function ‘int Decoder::Init(DecoderParameters&)’:
src/Decoder.cpp:16:75: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  decoderContext = avcodec_alloc_context3(state.parser->getStreamHandle()->codec->codec);

                                                                           ^
In file included from include/Parser.h:9:0,

                 from include/Decoder.h:3,

                 from src/Decoder.cpp:1:

/usr/local/include/libavformat/avformat.h:893:21: note: declared here

     AVCodecContext *codec;

                     ^
src/Decoder.cpp:16:75: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  decoderContext = avcodec_alloc_context3(state.parser->getStreamHandle()->codec->codec);


                                                                           ^
In file included from include/Parser.h:9:0,
                 from include/Decoder.h:3,

                 from src/Decoder.cpp:1:

/usr/local/include/libavformat/avformat.h:893:21: note: declared here
     AVCodecContext *codec;
                     ^
src/Decoder.cpp:16:75: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  decoderContext = avcodec_alloc_context3(state.parser->getStreamHandle()->codec->codec);
                                                                           ^
In file included from include/Parser.h:9:0,
                 from include/Decoder.h:3,
                 from src/Decoder.cpp:1:
/usr/local/include/libavformat/avformat.h:893:21: note: declared here
     AVCodecContext *codec;
                     ^
src/Decoder.cpp:22:78: error: ‘av_hwdevice_find_type_by_name’ was not declared in this scope
  deviceReference = av_hwdevice_ctx_alloc(av_hwdevice_find_type_by_name("cuda"));
                                                                              ^
src/Decoder.cpp:22:79: error: ‘av_hwdevice_ctx_alloc’ was not declared in this scope
  deviceReference = av_hwdevice_ctx_alloc(av_hwdevice_find_type_by_name("cuda"));
                                                                               ^
src/Decoder.cpp:23:2: error: ‘AVHWDeviceContext’ was not declared in this scope
  AVHWDeviceContext* deviceContext = (AVHWDeviceContext*) deviceReference->data;
  ^
src/Decoder.cpp:23:21: error: ‘deviceContext’ was not declared in this scope
  AVHWDeviceContext* deviceContext = (AVHWDeviceContext*) deviceReference->data;
                     ^
src/Decoder.cpp:23:56: error: expected primary-expression before ‘)’ token
  AVHWDeviceContext* deviceContext = (AVHWDeviceContext*) deviceReference->data;
                                                        ^
In file included from include/Parser.h:2:0,
                 from include/Decoder.h:3,
                 from src/Decoder.cpp:1:
src/Decoder.cpp:28:37: warning: suggest parentheses around comparison in operand of ‘!=’ [-Wparentheses]
  CHECK_STATUS(CUDAContext->cuda_ctx == nullptr);
                                     ^
include/Common.h:47:6: note: in definition of macro ‘CHECK_STATUS’
  if (status != 0) { \
      ^
src/Decoder.cpp:30:44: error: ‘av_hwdevice_ctx_init’ was not declared in this scope
  sts = av_hwdevice_ctx_init(deviceReference);
                                            ^
src/Decoder.cpp:33:71: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  sts = avcodec_open2(decoderContext, state.parser->getStreamHandle()->codec->codec, NULL);
                                                                       ^
In file included from include/Parser.h:9:0,
                 from include/Decoder.h:3,
                 from src/Decoder.cpp:1:
/usr/local/include/libavformat/avformat.h:893:21: note: declared here
     AVCodecContext *codec;
                     ^
src/Decoder.cpp:33:71: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  sts = avcodec_open2(decoderContext, state.parser->getStreamHandle()->codec->codec, NULL);
                                                                       ^
In file included from include/Parser.h:9:0,
                 from include/Decoder.h:3,
                 from src/Decoder.cpp:1:
/usr/local/include/libavformat/avformat.h:893:21: note: declared here
     AVCodecContext *codec;
                     ^
src/Decoder.cpp:33:71: warning: ‘AVStream::codec’ is deprecated [-Wdeprecated-declarations]
  sts = avcodec_open2(decoderContext, state.parser->getStreamHandle()->codec->codec, NULL);
                                                                       ^
In file included from include/Parser.h:9:0,
                 from include/Decoder.h:3,
                 from src/Decoder.cpp:1:
/usr/local/include/libavformat/avformat.h:893:21: note: declared here
     AVCodecContext *codec;
                     ^
src/Decoder.cpp: In function ‘void saveNV12(AVFrame*, FILE*)’:
src/Decoder.cpp:67:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (uint32_t i = 0; i < avFrame->height; i++) {
                         ^
src/Decoder.cpp:72:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (uint32_t i = 0; i < avFrame->height / 2; i++) {
                         ^
src/Decoder.cpp: In member function ‘int Decoder::Decode(AVPacket*)’:
src/Decoder.cpp:165:61: error: ‘av_hwframe_transfer_data’ was not declared in this scope
    sts = av_hwframe_transfer_data(NV12Frame, decodedFrame, 0);
                                                             ^
src/Decoder.cpp:129:10: warning: unused variable ‘start’ [-Wunused-variable]
  clock_t start = clock();
          ^
error: command 'gcc' failed with exit status 1
`
ffmpeg 4.0
`configuration: --enable-cuda --enable-cuvid --enable-nvenc --enable-nonfree --enable-libnpp --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64

  libavutil      55. 78.100 / 55. 78.100

  libavcodec     57.107.100 / 57.107.100

  libavformat    57. 83.100 / 57. 83.100

  libavdevice    57. 10.100 / 57. 10.100

  libavfilter     6.107.100 /  6.107.100

  libswscale      4.  8.100 /  4.  8.100

  libswresample   2.  9.100 /  2.  9.100

`
Would you mind to give me more hint?

Thank you again!

**Comment by BykadorovR** [comment]
I observed the same compilation issue with 3.4.6 FFmpeg version but neither with release/4.0 nor master.
Have you called make install && ldconfig after FFmpeg compilation so correct headers/libs used? Could you try also to build FFmpeg from master branch? I'll investigate your issue with Core dumped when reader.initialize().
Have you tried to execute simple.py with pre-defined test stream (rtmp://184.72.239.149/vod/mp4:bigbuckbunny_1500.mp4)?

**Comment by Lebron8997** [comment]
I did make install and add the ffmpeg lib path in $LD_LIBRARY_PATH in ~/.bashrc.

BTW, I feel pretty wired that 
libavutil/hwcontext.h:238:enum AVHWDeviceType av_hwdevice_find_type_by_name(const char *name);
but in your code Decoder.cpp  ibavutil/hwcontext.h was not quoted. How could it be?
Let me try master branch. Thank you for your patience!

**Comment by BykadorovR** [comment]
libavutil/hwcontext.h is included by other header files, in this case by libavformat/avformat.h -> libavcodec/avcodec.h via Parser.h

I reproduced your issue with 3.4.6 and the thing is that TensorStream fails with our test stream too: rtmp://184.72.239.149/vod/mp4:bigbuckbunny_1500.mp4. I don't see also that libavutil/hwcontext.h is included by libavformat/avformat.h so that's why we observe compilation error in case of 3.4.6 (https://github.com/FFmpeg/FFmpeg/blob/n3.4.6/libavcodec/avcodec.h)
In case of master (https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/avcodec.h) and release/4.0.0 (https://github.com/FFmpeg/FFmpeg/blob/release/4.0/libavcodec/avcodec.h) libavutil/hwcontext.h file included.

**Comment by Lebron8997** [comment]
@BykadorovR Thank you a lot for all your advice!

It finally works well with ffmpeg release/4.0.0.
In fact, I need extra lines for adding my own ffmpeg path in setup.py as follows:

ffmpeg_path = '/home/xl/inst/ffmpeg-zoo/ffmpeg-b4.0

include_path += [ffmpeg_path + "/include"]

library_path += [ffmpeg_path + "/lib"]
